[package]
name = "paperclip_parser"
version = "0.1.1"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2021"
exclude = []

[profile.release]
debug = false
opt-level = 3
lto = true

[lib]
name = "paperclip_parser"

[dependencies]
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83" }
paperclip_common = { path = "../rs-common" }
pretty_assertions = "1.2.1"
textwrap = "0.15.0"
glob = "0.3.0"
futures = "0.3.21"

