[workspace]
members = [
  "libs/compiler-react",
  "libs/cli",
  "libs/rs-common",
  "libs/project",
  "libs/evaluator",
  "libs/paperclip-loader",
  "libs/designer",
  "libs/proto"
]


[profile.release]
debug = false
opt-level = 3
lto = true

[profile.dev]
opt-level = 1              
overflow-checks = false    

