[package]
name = "paperclip_engine"
version = "0.1.1"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2021"
exclude = []

[profile.release]
debug = false
opt-level = 3
lto = true

[lib]
name = "paperclip_engine"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.72" }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
crc = "1.8.1"
pretty_assertions = "1.2.1"
textwrap = "0.15.0"
glob = "0.3.0"

