[package]
name = "paperclip_cli"
version = "0.1.1"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2021"
exclude = []

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
paperclip_engine = { path = "../engine" }
glob = "0.3.0"
serde = "1.0.143"

[dev-dependencies]
assert_cmd = "2.0.4"