[package]
name = "paperclip_runtime"
version = "0.1.1"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2021"
exclude = []

[profile.release]
debug = false
opt-level = 3
lto = true

[lib]
name = "paperclip_runtime"

[dependencies]
paperclip_parser = { path = "../parser" }
serde = { version = "1.0.143", features = ["derive"] }
paperclip_common = { path = "../rs-common" }
serde_json = { version = "1.0.83" }
anyhow = "1.0.61"
textwrap = "0.15.0"
futures = "0.3.21"
regex = "1.6.0"
lazy_static = "1.4.0"