[package]
name = "paperclip_local"
version = "0.1.1"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2021"
exclude = []

[profile.release]
debug = false
opt-level = 3
lto = true

[lib]
name = "paperclip_local"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
paperclip_parser = { path = "../parser" }
paperclip_runtime = { path = "../runtime" }
glob = "0.3.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83" }
anyhow = "1.0.61"
futures = "0.3.21"
path-absolutize = "3.0.13"

[dev-dependencies]
assert_cmd = "2.0.4"