[package]
name = "paperclip_cli"
version = "0.1.1"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2021"
exclude = []

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
paperclip_parser = { path = "../parser" }
paperclip_local = { path = "../rs-local" }
glob = "0.3.0"
serde = "1.0.143"
futures = "0.3.21"
futures-core = "0.3.24"
futures-util = "0.3.24"
anyhow = "1.0.61"

[dev-dependencies]
assert_cmd = "2.0.4"