[package]
name = "paperclip_project"
version = "0.1.1"
authors = ["Craig Condon <craig.j.condon@gmail.com>"]
edition = "2021"
exclude = []

[profile.release]
debug = false
opt-level = 3
lto = true

[lib]
name = "paperclip_project"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
paperclip_parser = { path = "../parser" }
paperclip_evaluator = { path = "../evaluator" }
paperclip_common = { path = "../rs-common" }
textwrap = "0.15.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83" }
anyhow = "1.0.61"
futures = "0.3.21"
futures-core = "0.3.24"
futures-util = "0.3.24"
path-absolutize = "3.0.13"
notify = "5.0.0"
wax = "0.5.0"
async-trait = "0.1.57"
async-stream = "0.3.3"

[dev-dependencies]
assert_cmd = "2.0.4"
